driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[kickstart::default]
